vlib leon/work
vcom -quiet leon/amba.vhd 
vcom -quiet leon/target.vhd 
vcom -quiet leon/device.vhd 
vcom -quiet leon/config.vhd 
vcom -quiet leon/mmuconfig.vhd 
vcom -quiet leon/sparcv8.vhd 
vcom -quiet leon/iface.vhd
vcom -quiet leon/macro.vhd
vcom -quiet leon/debug.vhd 
vcom -quiet leon/ambacomp.vhd 
vcom -quiet leon/multlib.vhd
vcom -quiet leon/tech_generic.vhd 
vcom -quiet leon/tech_proasic.vhd 
vcom -quiet leon/tech_axcel.vhd 
vcom -quiet leon/tech_atc18.vhd 
vcom -quiet leon/tech_tsmc25.vhd 
vcom -quiet leon/tech_atc35.vhd 
vcom -quiet leon/tech_atc25.vhd 
vcom -quiet leon/tech_atc18.vhd 
vcom -quiet leon/tech_umc18.vhd
vcom -quiet leon/tech_fs90.vhd 
vcom -quiet leon/bprom.vhd 
vcom -quiet leon/tech_virtex.vhd 
vcom -quiet leon/tech_virtex2.vhd 
vcom -quiet leon/tech_map.vhd
vcom -quiet leon/fpulib.vhd 
vcom -quiet leon/meiko.vhd 
vcom -quiet leon/fpu_lth.vhd 
vcom -quiet leon/fpu_core.vhd 
vcom -quiet leon/grfpc.vhd 
vcom -quiet leon/fp1eu.vhd 
vcom -quiet leon/mmu_icache.vhd
vcom -quiet leon/mmu_dcache.vhd
vcom -quiet leon/mmu_acache.vhd
vcom -quiet leon/mmutlbcam.vhd
vcom -quiet leon/mmulrue.vhd
vcom -quiet leon/mmulru.vhd
vcom -quiet leon/mmutlb.vhd
vcom -quiet leon/mmutw.vhd
vcom -quiet leon/mmu.vhd
vcom -quiet leon/mmu_cache.vhd

vcom -quiet leon/mul.vhd
vcom -quiet leon/div.vhd 
vcom -quiet leon/rstgen.vhd 
vcom -quiet leon/iu.vhd 
vcom -quiet leon/icache.vhd 
vcom -quiet leon/dcache.vhd
vcom -quiet leon/cachemem.vhd 
vcom -quiet leon/acache.vhd 
vcom -quiet leon/cache.vhd 
vcom -quiet leon/proc.vhd 
vcom -quiet leon/irqctrl2.vhd
vcom -quiet leon/apbmst.vhd 
vcom -quiet leon/ahbarb.vhd 
vcom -quiet leon/ahbram.vhd 
vcom -quiet leon/lconf.vhd 
vcom -quiet leon/wprot.vhd 
vcom -quiet leon/ahbtest.vhd 
vcom -quiet leon/ahbstat.vhd
vcom -quiet leon/timers.vhd 
vcom -quiet leon/irqctrl.vhd 
vcom -quiet leon/uart.vhd 
vcom -quiet leon/ioport.vhd 
vcom -quiet leon/sdmctrl.vhd
vcom -quiet leon/mctrl.vhd
vcom -quiet leon/ahbmst.vhd 
vcom -quiet leon/dcom_uart.vhd 
vcom -quiet leon/dcom.vhd 
vcom -quiet leon/dma.vhd 
vcom -quiet leon/dsu.vhd 
vcom -quiet leon/dsu_mem.vhd
vlog -quiet +incdir+leon leon/ethermac.v
vcom -quiet leon/pci_arb.vhd 
vcom -quiet leon/pci_gr.vhd 
vcom -quiet leon/pci.vhd 
vcom -quiet leon/eth_oc.vhd 
vcom -quiet leon/mcore.vhd
vcom -quiet leon/leon.vhd
vcom -quiet leon/leon_pci.vhd 
vcom -quiet leon/leon_eth_pci.vhd 
vcom -quiet leon/leon_eth.vhd 

vcom -quiet tbench/leonlib.vhd 
vcom -quiet tbench/iram.vhd 
vcom -quiet tbench/mt48lc16m16a2.vhd 
vcom -quiet tbench/testmod.vhd 
vcom -quiet tbench/mspram.vhd 
vcom -quiet tbench/bprom.vhd
vcom -quiet tbench/tbgen.vhd 
vcom -quiet tbench/tblib.vhd 
vcom -quiet tbench/tbdef.vhd 
vcom -quiet tbench/tbleon.vhd 
vcom -quiet tbench/tb_msp.vhd
