
read -dont_elaborate ../../leon/amba.vhd
read -dont_elaborate ../../leon/target.vhd
read -dont_elaborate ../../leon/device.vhd
read -dont_elaborate ../../leon/config.vhd
read -dont_elaborate ../../leon/sparcv8.vhd
read -dont_elaborate../../leon/mmuconfig.vhd
read -dont_elaborate ../../leon/iface.vhd
read -dont_elaborate ../../leon/macro.vhd
read -dont_elaborate ../../leon/bprom.vhd
read -dont_elaborate ../../leon/multlib.vhd
read -dont_elaborate ../../leon/ambacomp.vhd
read -dont_elaborate ../../leon/tech_generic.vhd
read -dont_elaborate ../../leon/tech_virtex.vhd
read -dont_elaborate ../../leon/tech_virtex2.vhd
read -dont_elaborate ../../leon/tech_atc18.vhd
read -dont_elaborate ../../leon/tech_atc25.vhd
read -dont_elaborate ../../leon/tech_atc35.vhd
read -dont_elaborate ../../leon/tech_fs90.vhd
read -dont_elaborate ../../leon/tech_umc18.vhd
read -dont_elaborate ../../leon/tech_tsmc25.vhd
read -dont_elaborate ../../leon/tech_proasic.vhd
read -dont_elaborate ../../leon/tech_axcel.vhd
read -dont_elaborate ../../leon/tech_map.vhd
read -dont_elaborate ../../leon/mmu_icache.vhd
read -dont_elaborate ../../leon/mmu_dcache.vhd
read -dont_elaborate ../../leon/mmu_acache.vhd
read -dont_elaborate ../../leon/mmutlbcam.vhd
read -dont_elaborate ../../leon/mmulrue.vhd
read -dont_elaborate ../../leon/mmulru.vhd
read -dont_elaborate ../../leon/mmutlb.vhd
read -dont_elaborate ../../leon/mmutw.vhd
read -dont_elaborate ../../leon/mmu.vhd
read -dont_elaborate ../../leon/mmu_cache.vhd
read -dont_elaborate ../../leon/cachemem.vhd
read -dont_elaborate ../../leon/icache.vhd
read -dont_elaborate ../../leon/dcache.vhd
read -dont_elaborate ../../leon/acache.vhd
read -dont_elaborate ../../leon/cache.vhd
read -dont_elaborate ../../leon/ahbmst.vhd
read -dont_elaborate ../../leon/dcom_uart.vhd
read -dont_elaborate ../../leon/dcom.vhd
read -dont_elaborate ../../leon/dsu_mem.vhd
read -dont_elaborate ../../leon/dsu.vhd
read -dont_elaborate ../../leon/apbmst.vhd
read -dont_elaborate ../../leon/ahbstat.vhd
read -dont_elaborate ../../leon/ahbtest.vhd
read -dont_elaborate ../../leon/ahbram.vhd
read -dont_elaborate ../../leon/ahbarb.vhd
read -dont_elaborate ../../leon/lconf.vhd
read -dont_elaborate ../../leon/fpulib.vhd
read -dont_elaborate ../../leon/ioport.vhd
read -dont_elaborate ../../leon/irqctrl.vhd
read -dont_elaborate ../../leon/irqctrl2.vhd
read -dont_elaborate ../../leon/sdmctrl.vhd
read -dont_elaborate ../../leon/mctrl.vhd
read -dont_elaborate ../../leon/rstgen.vhd
read -dont_elaborate ../../leon/timers.vhd
read -dont_elaborate ../../leon/uart.vhd
read -dont_elaborate ../../leon/mul.vhd
read -dont_elaborate ../../leon/div.vhd
read -dont_elaborate ../../leon/meiko.vhd
read -dont_elaborate ../../leon/fpu_lth.vhd
read -dont_elaborate ../../leon/fpu_core.vhd
read -dont_elaborate ../../leon/iu.vhd
read -dont_elaborate ../../leon/proc.vhd
read -dont_elaborate ../../leon/wprot.vhd
read -dont_elaborate ../../leon/mcore.vhd
read -dont_elaborate ../../leon/leon.vhd
elaborate leon -architecture rtl
