
all:

clean:
	cd gr-pci-xc2v; make clean
	cd gr-cpci-xc2v; make clean
	cd gr-xc3s1500; make clean
	cd avnet-xcv1000e; make clean
	cd tiggeler-xcv800; make clean
	cd billo-mblaze-xc2v; make clean

dist-clean: clean
	cd gr-pci-xc2v; make dist-clean
	cd gr-cpci-xc2v; make dist-clean
	cd gr-xc3s1500; make dist-clean
	cd avnet-xcv1000e; make dist-clean
	cd tiggeler-xcv800; make dist-clean
	cd billo-mblaze-xc2v; make dist-clean

